spring.application.name=inventory-service

spring.config.import=optional:configserver:http://localhost:8888
#############################################################
# SERVER
#############################################################

server.port=8087

#############################################################
# MYSQL
#############################################################

spring.datasource.url=jdbc:mysql://localhost:3306/inventorydb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=sujata

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#############################################################
# JPA
#############################################################

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#############################################################
# EUREKA
#############################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

#############################################################
# KAFKA CONNECTION
#############################################################

# Address of the Kafka broker (server) to which this application will connect.
# localhost:9092 means Kafka is running on the same machine on port 9092.
spring.kafka.bootstrap-servers=localhost:9092

#############################################################
# CONSUMER CONFIGURATION
#############################################################

# Consumer Group ID.
# All instances having the same group-id work together as one logical consumer.
# Kafka distributes partitions among consumers in the same group.
# Here, Inventory Service belongs to the "inventory-group".
spring.kafka.consumer.group-id=inventory-group


# Determines what should happen if no committed offset exists
# for this consumer group or the stored offset is no longer valid.
#
# earliest -> Read messages from the beginning of the topic.
# latest   -> Read only newly arriving messages.
#
# Useful during development because Inventory Service can replay
# all previously published Order events.
spring.kafka.consumer.auto-offset-reset=earliest


#############################################################
# DESERIALIZATION
#############################################################

# Kafka stores message keys as bytes.
# This converts the key from bytes into a Java String
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka stores message values as bytes.
# JsonDeserializer converts the JSON message into a Java object.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


#############################################################
# JSON DESERIALIZER SETTINGS
#############################################################

# Security setting for JsonDeserializer.
#
# Specifies which Java packages are allowed while converting JSON
# into Java objects.
#
# * means trust all packages.
#
# Good for learning projects.
# In production, specify your package instead, for example:
# com.sujata.inventoryservice.kafka
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# By default, Spring Kafka expects the producer to send Java class
# information inside Kafka headers.
#
# false means:
# "Ignore type information in Kafka headers."
#
# We will instead use the class specified below.
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# Since type headers are disabled, this property tells Spring
# which Java class should be created while deserializing JSON.
#
# Every incoming JSON message will be converted into an OrderEvent object.
spring.kafka.consumer.properties.spring.json.value.default.type=com.sujata.inventoryservice.kafka.OrderEvent


#############################################################
# APPLICATION-SPECIFIC PROPERTIES
#############################################################

# Name of the Kafka topic from which Inventory Service consumes
# Order Created events.
#
# Instead of hardcoding "order-created" inside Java code,
# we store it in the properties file.
app.kafka.topic.order-created=order-created

#############################################################
# ACTUATOR
#############################################################

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

#############################################################
# LOGGING
#############################################################

logging.level.root=INFO

logging.level.com.sujata.inventoryservice=DEBUG
