
#############################################################
# APPLICATION
#############################################################

spring.application.name=API-GATEWAY
server.port=9090

#############################################################
# EUREKA
#############################################################

# URL of Eureka Server where this gateway registers itself
# and discovers all available microservices.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Register the gateway using its IP address instead of hostname.
# Helps avoid hostname resolution issues in local environments.
eureka.instance.prefer-ip-address=true

#############################################################
# GATEWAY DISCOVERY
#############################################################

# Enables automatic service discovery using Eureka.
# The Gateway can locate registered services dynamically.
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# Converts service names to lowercase while generating routes.
# Example:
# PRODUCT-SERVICE -> product-service
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

#############################################################
# PRODUCT SERVICE ROUTE
#############################################################

# Unique identifier for this gateway route.
spring.cloud.gateway.server.webflux.routes[0].id=product-service

# Forward requests to Product Service using Eureka
# and Spring Cloud LoadBalancer.
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCT-SERVICE

# Any request matching this URL pattern
# will be routed to Product Service.
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/products/**


#############################################################
# CUSTOMER SERVICE ROUTE
#############################################################

spring.cloud.gateway.server.webflux.routes[1].id=customer-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/customers/**



#############################################################
# ORDER SERVICE ROUTE
#############################################################

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/orders/**


#############################################################
# INVENTORY SERVICE ROUTE
#############################################################
spring.cloud.gateway.server.webflux.routes[3].id=inventory-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/inventory/**


#############################################################
# PRODUCT SERVICE OPENAPI ROUTE
#############################################################

# Route used only for Product Service OpenAPI document.
spring.cloud.gateway.server.webflux.routes[4].id=product-service-docs
# Forward the request to Product Service.
spring.cloud.gateway.server.webflux.routes[4].uri=lb://PRODUCT-SERVICE
# When Swagger requests this URL...
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/product-service/v3/api-docs
# ...rewrite the request path before forwarding
# because Product Service exposes only /v3/api-docs.
spring.cloud.gateway.server.webflux.routes[4].filters[0]=SetPath=/v3/api-docs

#############################################################
# CUSTOMER SERVICE OPENAPI ROUTE
#############################################################

spring.cloud.gateway.server.webflux.routes[5].id=customer-service-docs
spring.cloud.gateway.server.webflux.routes[5].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/customer-service/v3/api-docs
spring.cloud.gateway.server.webflux.routes[5].filters[0]=SetPath=/v3/api-docs

#############################################################
# ORDER SERVICE OPENAPI ROUTE
#############################################################

spring.cloud.gateway.server.webflux.routes[6].id=order-service-docs
spring.cloud.gateway.server.webflux.routes[6].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/order-service/v3/api-docs
spring.cloud.gateway.server.webflux.routes[6].filters[0]=SetPath=/v3/api-docs


#############################################################
# ORDER SERVICE OPENAPI ROUTE
#############################################################

spring.cloud.gateway.server.webflux.routes[7].id=inventory-service-docs
spring.cloud.gateway.server.webflux.routes[7].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/inventory-service/v3/api-docs
spring.cloud.gateway.server.webflux.routes[7].filters[0]=SetPath=/v3/api-docs

#############################################################
# CENTRAL SWAGGER UI
#############################################################

# Display name of Product Service in Swagger UI dropdown.
springdoc.swagger-ui.urls[0].name=Product Service
# OpenAPI URL for Product Service.
springdoc.swagger-ui.urls[0].url=/product-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Customer Service
springdoc.swagger-ui.urls[1].url=/customer-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=Order Service
springdoc.swagger-ui.urls[2].url=/order-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=Inventory Service
springdoc.swagger-ui.urls[3].url=/inventory-service/v3/api-docs
